; SFX indexes (see audio/sfx_pointers.asm)
	const_def
	const SFX_ITEM                        ; 00
	const SFX_CAUGHT_MON                  ; 01
	const SFX_POKEBALLS_PLACED_ON_TABLE   ; 02
	const SFX_POTION                      ; 03
	const SFX_FULL_HEAL                   ; 04
	const SFX_MENU                        ; 05
	const SFX_READ_TEXT                   ; 06
	const SFX_DEX_FANFARE_20_49           ; 07
	const SFX_DEX_FANFARE_80_109          ; 08
	const SFX_POISON                      ; 09
	const SFX_GOT_SAFARI_BALLS            ; 0a
	const SFX_BOOT_PC                     ; 0b
	const SFX_SHUT_DOWN_PC                ; 0c
	const SFX_CHOOSE_PC_OPTION            ; 0d
	const SFX_ESCAPE_ROPE                 ; 0e
	const SFX_PUSH_BUTTON                 ; 0f
	const SFX_SECOND_PART_OF_ITEMFINDER   ; 10
	const SFX_WARP_TO                     ; 11
	const SFX_WARP_FROM                   ; 12
	const SFX_CHANGE_DEX_MODE             ; 13
	const SFX_JUMP_OVER_LEDGE             ; 14
	const SFX_GRASS_RUSTLE                ; 15
	const SFX_FLY                         ; 16
	const SFX_WRONG                       ; 17
	const SFX_SQUEAK                      ; 18
	const SFX_STRENGTH                    ; 19
	const SFX_BOAT                        ; 1a
	const SFX_WALL_OPEN                   ; 1b
	const SFX_PLACE_PUZZLE_PIECE_DOWN     ; 1c
	const SFX_ENTER_DOOR                  ; 1d
	const SFX_SWITCH_POKEMON              ; 1e
	const SFX_TALLY                       ; 1f
	const SFX_TRANSACTION                 ; 20
	const SFX_EXIT_BUILDING               ; 21
	const SFX_BUMP                        ; 22
	const SFX_SAVE                        ; 23
	const SFX_POKEFLUTE                   ; 24
	const SFX_ELEVATOR_END                ; 25
	const SFX_THROW_BALL                  ; 26
	const SFX_BALL_POOF                   ; 27
	const SFX_FAINT                       ; 28
	const SFX_RUN                         ; 29
	const SFX_SLOT_MACHINE_START          ; 2a
	const SFX_FANFARE                     ; 2b
	const SFX_PECK                        ; 2c
	const SFX_KINESIS                     ; 2d
	const SFX_LICK                        ; 2e
	const SFX_POUND                       ; 2f
	const SFX_MOVE_PUZZLE_PIECE           ; 30
	const SFX_COMET_PUNCH                 ; 31
	const SFX_MEGA_PUNCH                  ; 32
	const SFX_SCRATCH                     ; 33
	const SFX_VICEGRIP                    ; 34
	const SFX_RAZOR_WIND                  ; 35
	const SFX_CUT                         ; 36
	const SFX_WING_ATTACK                 ; 37
	const SFX_WHIRLWIND                   ; 38
	const SFX_BIND                        ; 39
	const SFX_VINE_WHIP                   ; 3a
	const SFX_DOUBLE_KICK                 ; 3b
	const SFX_MEGA_KICK                   ; 3c
	const SFX_HEADBUTT                    ; 3d
	const SFX_HORN_ATTACK                 ; 3e
	const SFX_TACKLE                      ; 3f
	const SFX_POISON_STING                ; 40
	const SFX_POWDER                      ; 41
	const SFX_DOUBLESLAP                  ; 42
	const SFX_BITE                        ; 43
	const SFX_JUMP_KICK                   ; 44
	const SFX_STOMP                       ; 45
	const SFX_TAIL_WHIP                   ; 46
	const SFX_KARATE_CHOP                 ; 47
	const SFX_SUBMISSION                  ; 48
	const SFX_WATER_GUN                   ; 49
	const SFX_SWORDS_DANCE                ; 4a
	const SFX_THUNDER                     ; 4b
	const SFX_SUPERSONIC                  ; 4c
	const SFX_LEER                        ; 4d
	const SFX_EMBER                       ; 4e
	const SFX_BUBBLEBEAM                  ; 4f
	const SFX_HYDRO_PUMP                  ; 50
	const SFX_SURF                        ; 51
	const SFX_PSYBEAM                     ; 52
	const SFX_CHARGE                      ; 53
	const SFX_THUNDERSHOCK                ; 54
	const SFX_PSYCHIC                     ; 55
	const SFX_SCREECH                     ; 56
	const SFX_BONE_CLUB                   ; 57
	const SFX_SHARPEN                     ; 58
	const SFX_EGG_BOMB                    ; 59
	const SFX_SING                        ; 5a
	const SFX_HYPER_BEAM                  ; 5b
	const SFX_SHINE                       ; 5c
	const SFX_UNKNOWN_5F                  ; 5d
	const SFX_UNKNOWN_60                  ; 5e
	const SFX_UNKNOWN_61                  ; 5f
	const SFX_SWITCH_POCKETS              ; 60
	const SFX_UNKNOWN_63                  ; 61
	const SFX_BURN                        ; 62
	const SFX_TITLE_SCREEN_ENTRANCE       ; 63
	const SFX_UNKNOWN_66                  ; 64
	const SFX_GET_COIN_FROM_SLOTS         ; 65
	const SFX_PAY_DAY                     ; 66
	const SFX_METRONOME                   ; 67
	const SFX_CALL                        ; 68
	const SFX_HANG_UP                     ; 69
	const SFX_NO_SIGNAL                   ; 6a
	const SFX_SANDSTORM                   ; 6b
	const SFX_ELEVATOR                    ; 6c
	const SFX_PROTECT                     ; 6d
	const SFX_SKETCH                      ; 6e
	const SFX_RAIN_DANCE                  ; 6f
	const SFX_AEROBLAST                   ; 70
	const SFX_SPARK                       ; 71
	const SFX_CURSE                       ; 72
	const SFX_RAGE                        ; 73
	const SFX_THIEF                       ; 74
	const SFX_THIEF_2                     ; 75
	const SFX_SPIDER_WEB                  ; 76
	const SFX_MIND_READER                 ; 77
	const SFX_NIGHTMARE                   ; 78
	const SFX_SNORE                       ; 79
	const SFX_SWEET_KISS                  ; 7a
	const SFX_SWEET_KISS_2                ; 7b
	const SFX_BELLY_DRUM                  ; 7c
	const SFX_TOXIC                       ; 7d
	const SFX_SLUDGE_BOMB                 ; 7e
	const SFX_FORESIGHT                   ; 7f
	const SFX_SPITE                       ; 80
	const SFX_OUTRAGE                     ; 81
	const SFX_PERISH_SONG                 ; 82
	const SFX_GIGA_DRAIN                  ; 83
	const SFX_ATTRACT                     ; 84
	const SFX_KINESIS_2                   ; 85
	const SFX_ZAP_CANNON                  ; 86
	const SFX_MEAN_LOOK                   ; 87
	const SFX_HEAL_BELL                   ; 88
	const SFX_RETURN                      ; 89
	const SFX_EXP_BAR                     ; 8a
	const SFX_MILK_DRINK                  ; 8b
	const SFX_PRESENT                     ; 8c
	const SFX_MORNING_SUN                 ; 8d
	const SFX_LEVEL_UP                    ; 8e
	const SFX_KEY_ITEM                    ; 8f
	const SFX_FANFARE_2                   ; 90
	const SFX_REGISTER_PHONE_NUMBER       ; 91
	const SFX_3RD_PLACE                   ; 92
	const SFX_GET_EGG_UNUSED              ; 93
	const SFX_GET_EGG                     ; 94
	const SFX_MOVE_DELETED                ; 95
	const SFX_2ND_PLACE                   ; 96
	const SFX_1ST_PLACE                   ; 97
	const SFX_CHOOSE_A_CARD               ; 98
	const SFX_GET_TM                      ; 99
	const SFX_GET_BADGE                   ; 9a
	const SFX_QUIT_SLOTS                  ; 9b
	const SFX_EGG_CRACK                   ; 9c
	const SFX_DEX_FANFARE_LESS_THAN_20    ; 9d
	const SFX_DEX_FANFARE_140_169         ; 9e
	const SFX_DEX_FANFARE_170_199         ; 9f
	const SFX_DEX_FANFARE_200_229         ; a0
	const SFX_DEX_FANFARE_230_PLUS        ; a1
	const SFX_EVOLVED                     ; a2
	const SFX_MASTER_BALL                 ; a3
	const SFX_EGG_HATCH                   ; a4
	const SFX_GS_INTRO_CHARIZARD_FIREBALL ; a5
	const SFX_GS_INTRO_POKEMON_APPEARS    ; a6
	const SFX_FLASH                       ; a7
	const SFX_GAME_FREAK_LOGO_GS          ; a8
	const SFX_NOT_VERY_EFFECTIVE          ; a9
	const SFX_DAMAGE                      ; aa
	const SFX_SUPER_EFFECTIVE             ; ab
	const SFX_BALL_BOUNCE                 ; ac
	const SFX_MOONLIGHT                   ; ad
	const SFX_ENCORE                      ; ae
	const SFX_BEAT_UP                     ; af
	const SFX_BATON_PASS                  ; b0
	const SFX_BALL_WOBBLE                 ; b1
	const SFX_SWEET_SCENT                 ; b2
	const SFX_SWEET_SCENT_2               ; b3
	const SFX_HIT_END_OF_EXP_BAR          ; b4
	const SFX_GIVE_TRADEMON               ; b5
	const SFX_GET_TRADEMON                ; b6
	const SFX_TRAIN_ARRIVED               ; b7
	const SFX_STOP_SLOT                   ; b8
	const SFX_2_BOOPS                     ; b9
; new to Crystal
	const SFX_GLASS_TING                  ; ba
	const SFX_GLASS_TING_2                ; bb
	const SFX_INTRO_UNOWN_1               ; bc
	const SFX_INTRO_UNOWN_2               ; bd
	const SFX_INTRO_UNOWN_3               ; be
	const SFX_DITTO_POP_UP                ; bf
	const SFX_DITTO_TRANSFORM             ; c0
	const SFX_INTRO_SUICUNE_1             ; c1
	const SFX_INTRO_PICHU                 ; c2
	const SFX_INTRO_SUICUNE_2             ; c3
	const SFX_INTRO_SUICUNE_3             ; c4
	const SFX_DITTO_BOUNCE                ; c5
	const SFX_INTRO_SUICUNE_4             ; c6
	const SFX_GAME_FREAK_PRESENTS         ; c7
	const SFX_TINGLE                      ; c8
	const SFX_INTRO_WHOOSH                ; c9
	const SFX_TWO_PC_BEEPS                ; ca
	const SFX_4_NOTE_DITTY                ; cb
	const SFX_TWINKLE                     ; cc
	const SFX_PETAL_DANCE                 ; cd
NUM_SFX EQU const_value
