command: MACRO
	const \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	const_def 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command resetstats              ; 1f
	command storeenergy             ; 20
	command unleashenergy           ; 21
	command forceswitch             ; 22
	command endloop                 ; 23
	command flinchtarget            ; 24
	command ohko                    ; 25
	command recoil                  ; 26
	command mist                    ; 27
	command focusenergy             ; 28
	command confuse                 ; 29
	command confusetarget           ; 2a
	command heal                    ; 2b
	command transform               ; 2c
	command screen                  ; 2d
	command poison                  ; 2e
	command paralyze                ; 2f
	command substitute              ; 30
	command rechargenextturn        ; 31
	command metronome               ; 32
	command leechseed               ; 33
	command disable                 ; 34
	command cleartext               ; 35
	command charge                  ; 36
	command checkcharge             ; 37
	command traptarget              ; 38
	command checkfloatmon           ; 39
	command rampage                 ; 3a
	command checkrampage            ; 3b
	command constantdamage          ; 3c
	command counter                 ; 3d
	command encore                  ; 3e
	command snore                   ; 3f
	command conversion2             ; 40
	command lockon                  ; 41
	command sketch                  ; 42
	command sleeptalk               ; 43
	command destinybond             ; 44
	command spite                   ; 45
	command falseswipe              ; 46
	command healbell                ; 47
	command kingsrock               ; 48
	command triplekick              ; 49
	command kickcounter             ; 4a
	command thief                   ; 4b
	command arenatrap               ; 4c
	command nightmare               ; 4d
	command flamewheel              ; 4e
	command curse                   ; 4f
	command protect                 ; 50
	command spikes                  ; 51
	command foresight               ; 52
	command perishsong              ; 53
	command startsandstorm          ; 54
	command endure                  ; 55
	command checkrollout            ; 56
	command rolloutpower            ; 57
	command furycutter              ; 58
	command attract                 ; 59
	command happinesspower          ; 5a
	command present                 ; 5b
	command damagecalc              ; 5c
	command safeguard               ; 5d
	command checksafeguard          ; 5e
	command getmagnitude            ; 5f
	command batonpass               ; 60
	command pursuit                 ; 61
	command clearhazards            ; 62
	command uturn                   ; 63
	command healsun                 ; 64
	command hiddenpower             ; 65
	command startrain               ; 66
	command startsun                ; 67
	command attackup                ; 68
	command defenseup               ; 69
	command speedup                 ; 6a
	command specialattackup         ; 6b
	command specialdefenseup        ; 6c
	command accuracyup              ; 6d
	command evasionup               ; 6e
	command attackup2               ; 6f
	command defenseup2              ; 70
	command speedup2                ; 71
	command specialattackup2        ; 72
	command specialdefenseup2       ; 73
	command accuracyup2             ; 74
	command evasionup2              ; 75
	command attackdown              ; 76
	command defensedown             ; 77
	command speeddown               ; 78
	command specialattackdown       ; 79
	command specialdefensedown      ; 7a
	command accuracydown            ; 7b
	command evasiondown             ; 7c
	command attackdown2             ; 7d
	command defensedown2            ; 7e
	command speeddown2              ; 7f
	command specialattackdown2      ; 80
	command specialdefensedown2     ; 81
	command accuracydown2           ; 82
	command evasiondown2            ; 83
	command statupmessage           ; 84
	command statdownmessage         ; 85
	command statupfailtext          ; 86
	command statdownfailtext        ; 87
	command effectchance            ; 88
	command statdownanim            ; 89
	command statupanim              ; 8a
	command switchturn              ; 8b
	command bellydrum               ; 8c
	command psychup                 ; 8d
	command rage                    ; 8e
	command doubleflyingdamage      ; 8f
	command doubleundergrounddamage ; 90
	command mirrorcoat              ; 91
	command checkfuturesight        ; 92
	command futuresight             ; 93
	command doubleminimizedamage    ; 94
	command skipsuncharge           ; 95
	command starthail               ; 96
	command beatup                  ; 97
	command ragedamage              ; 98
	command resettypematchup        ; 99
	command allstatsup              ; 9a
	command bidefailtext            ; 9b
	command raisesubnoanim          ; 9c
	command lowersubnoanim          ; 9d
	command beatupfailtext          ; 9e
	command clearmissdamage         ; 9f
	command movedelay               ; a0
	command moveanim                ; a1
	command tristatuschance         ; a2
	command supereffectivelooptext  ; a3
	command startloop               ; a4
	command curl                    ; a5
	command undergroundflyer        ; a6
	command checkcontact            ; a7
	command doubledamageifhit       ; a8
NUM_EFFECT_COMMANDS EQU const_value - 1

	const_def -1, -1
	command endmove                 ; ff
	command endturn                 ; fe
