command: MACRO
	const \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	const_def 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command resetstats              ; 1f
	command storeenergy             ; 20
	command unleashenergy           ; 21
	command forceswitch             ; 22
	command endloop                 ; 23
	command flinchtarget            ; 24
	command ohko                    ; 25
	command recoil                  ; 26
	command mist                    ; 27
	command focusenergy             ; 28
	command confuse                 ; 29
	command confusetarget           ; 2a
	command heal                    ; 2b
	command transform               ; 2c
	command screen                  ; 2d
	command poison                  ; 2e
	command paralyze                ; 2f
	command substitute              ; 30
	command rechargenextturn        ; 31
	command metronome               ; 32
	command leechseed               ; 33
	command disable                 ; 34
	command cleartext               ; 35
	command charge                  ; 36
	command checkcharge             ; 37
	command traptarget              ; 38
	command checkfloatmon           ; 39
	command rampage                 ; 3a
	command checkrampage            ; 3b
	command constantdamage          ; 3c
	command counter                 ; 3d
	command encore                  ; 3e
	command snore                   ; 3f
	command lockon                  ; 40
	command sketch                  ; 41
	command sleeptalk               ; 42
	command destinybond             ; 43
	command spite                   ; 44
	command falseswipe              ; 45
	command healbell                ; 46
	command kingsrock               ; 47
	command triplekick              ; 48
	command kickcounter             ; 49
	command thief                   ; 4a
	command arenatrap               ; 4b
	command nightmare               ; 4c
	command flamewheel              ; 4d
	command curse                   ; 4e
	command protect                 ; 4f
	command spikes                  ; 50
	command foresight               ; 51
	command perishsong              ; 52
	command startsandstorm          ; 53
	command noitemdamage            ; 54
	command checkrollout            ; 55
	command rolloutpower            ; 56
	command furycutter              ; 57
	command attract                 ; 58
	command happinesspower          ; 59
	command present                 ; 5a
	command damagecalc              ; 5b
	command safeguard               ; 5c
	command checksafeguard          ; 5d
	command getmagnitude            ; 5e
	command batonpass               ; 5f
	command pursuit                 ; 60
	command clearhazards            ; 61
	command uturn                   ; 62
	command healsun                 ; 63
	command hiddenpower             ; 64
	command startrain               ; 65
	command startsun                ; 66
	command attackup                ; 67
	command defenseup               ; 68
	command speedup                 ; 69
	command specialattackup         ; 6a
	command specialdefenseup        ; 6b
	command accuracyup              ; 6c
	command evasionup               ; 6d
	command attackup2               ; 6e
	command defenseup2              ; 6f
	command speedup2                ; 70
	command specialattackup2        ; 71
	command specialdefenseup2       ; 72
	command accuracyup2             ; 73
	command evasionup2              ; 74
	command attackdown              ; 75
	command defensedown             ; 76
	command speeddown               ; 77
	command specialattackdown       ; 78
	command specialdefensedown      ; 79
	command accuracydown            ; 7a
	command evasiondown             ; 7b
	command attackdown2             ; 7c
	command defensedown2            ; 7d
	command speeddown2              ; 7e
	command specialattackdown2      ; 7f
	command specialdefensedown2     ; 80
	command accuracydown2           ; 81
	command evasiondown2            ; 82
	command statupmessage           ; 83
	command statdownmessage         ; 84
	command statupfailtext          ; 85
	command statdownfailtext        ; 86
	command effectchance            ; 87
	command statdownanim            ; 88
	command statupanim              ; 89
	command switchturn              ; 8a
	command bellydrum               ; 8b
	command psychup                 ; 8c
	command rage                    ; 8d
	command doubleflyingdamage      ; 8e
	command doubleundergrounddamage ; 8f
	command mirrorcoat              ; 90
	command checkfuturesight        ; 91
	command futuresight             ; 92
	command doubleminimizedamage    ; 93
	command skipsuncharge           ; 94
	command starthail               ; 95
	command beatup                  ; 96
	command ragedamage              ; 97
	command resettypematchup        ; 98
	command allstatsup              ; 99
	command bidefailtext            ; 9a
	command raisesubnoanim          ; 9b
	command lowersubnoanim          ; 9c
	command beatupfailtext          ; 9d
	command clearmissdamage         ; 9e
	command movedelay               ; 9f
	command moveanim                ; a0
	command tristatuschance         ; a1
	command supereffectivelooptext  ; a2
	command startloop               ; a3
	command curl                    ; a4
	command undergroundflyer        ; a5
	command checkcontact            ; a6
	command doubledamageifhit       ; a7
NUM_EFFECT_COMMANDS EQU const_value - 1

	const_def -1, -1
	command endmove                 ; ff
	command endturn                 ; fe
