	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, BROWN
	tilepal 0, ROOF, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GREEN, GREEN, BROWN
	tilepal 0, ROOF, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, RED, GRAY, GRAY, GRAY, BROWN, GRAY
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY
	tilepal 0, GRAY, GRAY, RED, GRAY, GRAY, GRAY, BROWN, GRAY
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, RED, BROWN, BROWN, GRAY, GRAY, ROOF
	tilepal 0, GRAY, ROOF, GRAY, GRAY, ROOF, ROOF, RED, ROOF

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, BROWN
	tilepal 1, ROOF, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, WATER, GREEN, GREEN, BROWN
	tilepal 1, ROOF, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, GRAY, RED, GRAY, GRAY, GRAY, BROWN, GRAY
	tilepal 1, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY
	tilepal 1, GRAY, GRAY, RED, GRAY, GRAY, GRAY, BROWN, GRAY
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, GRAY, RED, BROWN, BROWN, GRAY, GRAY, ROOF
	tilepal 1, GRAY, ROOF, GRAY, GRAY, ROOF, ROOF, RED, ROOF
