	tilepal 0, ROOF, YELLOW, YELLOW, GREEN, GREEN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, ROOF
	tilepal 0, RED, YELLOW, YELLOW, GREEN, GREEN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, RED, RED, ROOF, ROOF, YELLOW, YELLOW, BROWN, BROWN
	tilepal 0, WATER, WATER, TEXT, TEXT, GRAY, GRAY, ROOF, ROOF
	tilepal 0, RED, RED, ROOF, ROOF, YELLOW, YELLOW, BROWN, BROWN
	tilepal 0, WATER, WATER, TEXT, TEXT, GRAY, GRAY, ROOF, ROOF
