	object_const_def
	const SEAFOAMCAVEUPPERFLOORS_BOULDER1
	const SEAFOAMCAVEUPPERFLOORS_BOULDER2
	const SEAFOAMCAVEUPPERFLOORS_BOULDER3
	const SEAFOAMCAVEUPPERFLOORS_BOULDER4
	const SEAFOAMCAVEUPPERFLOORS_BOULDER5
	const SEAFOAMCAVEUPPERFLOORS_BOULDER6

SeafoamCaveUpperFloors_MapScripts:
	def_scene_scripts

	def_callbacks
	callback MAPCALLBACK_OBJECTS, .BoulderStartPositions
	callback MAPCALLBACK_STONETABLE, .SetUpStoneTable

.BoulderStartPositions:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER1
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER2
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER3
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER4
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER5
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER6
	checkevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1A
	iftrue .Check1B
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER1
.Check2A:
	checkevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2A
	iftrue .Check2B
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER2
	endcallback

.Check1B:
	checkevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1B
	iftrue .Do1B
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER3
	sjump .Check2A

.Do1B:
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER5
	sjump .Check2A

.Check2B:
	checkevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2B
	iftrue .Do2B
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER4
	endcallback

.Do2B:
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER6
	endcallback

.SetUpStoneTable:
	usestonetable .StoneTable
 	endcallback

.StoneTable:
	stonetable  6, SEAFOAMCAVEUPPERFLOORS_BOULDER1, .Boulder1
	stonetable  7, SEAFOAMCAVEUPPERFLOORS_BOULDER2, .Boulder2
	stonetable 17, SEAFOAMCAVEUPPERFLOORS_BOULDER3, .Boulder3
	stonetable 18, SEAFOAMCAVEUPPERFLOORS_BOULDER4, .Boulder4
	stonetable 28, SEAFOAMCAVEUPPERFLOORS_BOULDER5, .Boulder5
	stonetable 29, SEAFOAMCAVEUPPERFLOORS_BOULDER6, .Boulder6
	db -1 ; end

.Boulder1:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER1
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER3
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1A
	sjump .Fall

.Boulder2:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER2
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER4
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2A
	sjump .Fall

.Boulder3:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER3
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER5
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1B
	sjump .Fall

.Boulder4:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER4
	appear SEAFOAMCAVEUPPERFLOORS_BOULDER6
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2B
.Fall:
	pause 30
	playsound SFX_STRENGTH
	earthquake 80
	opentext
	writetext SeafoamCaveUpperFloorsBoulderFellText
	waitbutton
	closetext
	end

.Boulder5:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER5
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1C
	sjump .Splash

.Boulder6:
	disappear SEAFOAMCAVEUPPERFLOORS_BOULDER6
	setevent EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2C
.Splash:
	pause 30
	playsound SFX_HYDRO_PUMP
	earthquake 80
	opentext
	writetext SeafoamCaveUpperFloorsBoulderSplashText
	waitbutton
	closetext
	end

SeafoamCaveUpperFloorsBoulder:
	jumpstd StrengthBoulderScript

SeafoamCaveUpperFloorsHiddenXSpDefend:
	hiddenitem X_SP_DEFEND, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_HIDDEN_X_SP_DEFEND

SeafoamCaveUpperFloorsBoulderFellText:
	text "Hole in one!"
	done

SeafoamCaveUpperFloorsBoulderSplashText:
	text "Sounds like it"
	line "landed in water…"
	done

SeafoamCaveUpperFloors_MapEvents:
	def_warp_events
	warp_event  3, 13, SEAFOAM_CAVE_PUZZLE_CHAMBER, 3
	warp_event 29, 15, SEAFOAM_GYM, 2
	warp_event  9,  5, SEAFOAM_CAVE_UPPER_FLOORS, 10
	warp_event 27,  3, SEAFOAM_CAVE_UPPER_FLOORS, 11
	warp_event 25, 15, SEAFOAM_CAVE_UPPER_FLOORS, 12
	warp_event 19,  6, SEAFOAM_CAVE_UPPER_FLOORS, 8 ; hole
	warp_event 26,  6, SEAFOAM_CAVE_UPPER_FLOORS, 9 ; hole
	warp_event 18, 29, SEAFOAM_CAVE_UPPER_FLOORS, 6 ; landing
	warp_event 23, 29, SEAFOAM_CAVE_UPPER_FLOORS, 7 ; landing
	warp_event  7, 27, SEAFOAM_CAVE_UPPER_FLOORS, 3
	warp_event 25, 25, SEAFOAM_CAVE_UPPER_FLOORS, 4
	warp_event 23, 37, SEAFOAM_CAVE_UPPER_FLOORS, 5
	warp_event  3, 25, SEAFOAM_CAVE_UPPER_FLOORS, 21
	warp_event 13, 27, SEAFOAM_CAVE_UPPER_FLOORS, 22
	warp_event 19, 37, SEAFOAM_CAVE_UPPER_FLOORS, 23
	warp_event 25, 33, SEAFOAM_CAVE_UPPER_FLOORS, 24
	warp_event 18, 28, SEAFOAM_CAVE_UPPER_FLOORS, 19 ; hole
	warp_event 23, 28, SEAFOAM_CAVE_UPPER_FLOORS, 20 ; hole
	warp_event 19, 49, SEAFOAM_CAVE_UPPER_FLOORS, 17 ; landing
	warp_event 22, 49, SEAFOAM_CAVE_UPPER_FLOORS, 18 ; landing
	warp_event  5, 45, SEAFOAM_CAVE_UPPER_FLOORS, 13
	warp_event 13, 49, SEAFOAM_CAVE_UPPER_FLOORS, 14
	warp_event 19, 57, SEAFOAM_CAVE_UPPER_FLOORS, 15
	warp_event 25, 53, SEAFOAM_CAVE_UPPER_FLOORS, 16
	warp_event  5, 55, SEAFOAM_CAVE_LOWER_FLOORS, 3
	warp_event 25, 45, SEAFOAM_CAVE_LOWER_FLOORS, 4
	warp_event 25, 55, SEAFOAM_CAVE_LOWER_FLOORS, 5
	warp_event 19, 48, SEAFOAM_CAVE_LOWER_FLOORS, 1 ; hole
	warp_event 22, 48, SEAFOAM_CAVE_LOWER_FLOORS, 2 ; hole

	def_coord_events

	def_bg_events
	bg_event 15, 57, BGEVENT_ITEM, SeafoamCaveUpperFloorsHiddenXSpDefend

	def_object_events
	object_event 22, 12, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_1
	object_event 29, 11, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_2
	object_event 17, 28, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_3
	object_event 24, 28, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_4
	object_event 18, 48, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_5
	object_event 23, 48, SPRITE_BOULDER, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, OBJECTTYPE_SCRIPT, 0, SeafoamCaveUpperFloorsBoulder, EVENT_SEAFOAM_CAVE_UPPER_FLOORS_BOULDER_6
