PikachuAnimationIdlePointers:
	table_width 2, PikachuAnimationIdlePointers
	dw RetroPikachuAnimationIdle
	dw SilverPikachuAnimationIdle
	dw CrystalPikachuAnimationIdle
	dw FightingPikachuAnimationIdle
	dw SurfingPikachuAnimationIdle
	dw FlyingPikachuAnimationIdle
	assert_table_length NUM_PIKACHU_FORMS
